sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t lixinio/mysql:5.6 .

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push lixinio/mysql:5.6
